default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: deploy
  password: <%= a password %>
development:
  <<: *default
  database: music_studio_api_development
test:
  <<: *default
  database: music_studio_api_test
production:
  <<: *default
  database: music_studio_api_production
