default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy
  password: pointer
development:
  <<: *default
  database: music_studio_api_development
test:
  <<: *default
  database: music_studio_api_test
production:
  <<: *default
  database: music_studio_api_production
